### ISSUE TITLE
Missing release tag: v2.1.1

### ISSUE THREAD

**Issue by jmkim** [AmanoTeam/duckpy#1]
Hi,

I can see the commit https://github.com/AmanoTeam/duckpy/commit/a6981bbcdc0432dfb0a512ebd6e5d257db923c24 which bumped the version to `2.1.1`:

https://github.com/AmanoTeam/duckpy/blob/a6981bbcdc0432dfb0a512ebd6e5d257db923c24/setup.py#L8

But cannot follow the same release in [GitHub releases](https://github.com/AmanoTeam/duckpy/releases).

Thank you!

**Comment by alissonlauffer** [comment]
I forgot to make a release in GitHub. Thanks for pointing out that.

**Comment by jmkim** [comment]
So lovely! Thank you for solving this very fast \o/
