### ISSUE TITLE
How can I display more information?

### ISSUE THREAD

**Issue by qlofly** [AmanoTeam/duckpy#5]
Hi. 
When requesting "client.search" I get 30 responses. Can I increase this number?

**Comment by alissonlauffer** [comment]
For now, no. DuckDuckGo has pagination support, but it does not seem to work inside duckpy (Well, sometimes it does not even work in DuckDuckGo itself, making it return an empty result page).

Also its parameters does not make much sense:
![image](https://user-images.githubusercontent.com/29029632/103155305-50fa5800-477d-11eb-8b9f-a4f6646a0ea9.png)

**Comment by qlofly** [comment]
Are there any plans to implement this feature?
